#!/bin/bash

help_message() {
    echo "Usage: getpack [options] user repo...
Options:
  -h, --help:              Display this information.
  -i, --install:           Installs the script.
  -u, --uninstall:         Uninstalls the script, deleting it."
}

num_args=$#

# Flags section
help=0
install=0
uninstall=0

if [[ $# -eq 1 ]]; then
  if [[ "$1" == "-i" || "$1" == "--install" ]]; then
    echo "Used the install flag"
    exit 1
  elif [[ "$1" == "-u" || "$1" == "--uninstall" ]]; then
    echo "Used the uninstall flag"
    exit 1
  elif [[ "$1" == "-h" || "$1" == "--help" ]]; then
    help_message
    exit 1
  fi
else
  echo "wtf is this"
  exit 1
fi

repo_user="$1"
repo_name="$2"

repository_url="https://github.com/$repo_user/$repo_name/archive/refs/heads/main.zip"

destination_dir=$(pwd)

echo "Downloading $repo_name from $repo_user..."
sudo wget -O $destination_dir/$repo_name.zip $repository_url -q

# Check if the download was successful
if [ $? -eq 0 ]; then
  echo "Download successful, extracting the repository..."
  # Extract the zipball
  unzip $destination_dir/$repo_name.zip -d $destination_dir
  # Remove the zip file
  rm -f $destination_dir/$repo_name.zip
  # Move the extracted files to the correct directory
  mv $destination_dir/$repo_name-main $destination_dir/$repo_name
  rm -rf $destination_dir/$repo_name-main

  echo "Repository $repo_name downloaded and extracted to $destination_dir"
else
  echo "Failed to download the repository"
  rm .zip
fi